const QueryKey = {
  COUNTRIES_FLAGS_IMPORT: 'COUNTRIES_FLAGS_IMPORT',
  CURRENT_USER: 'CURRENT_USER',
  EMAIL_CONFIRM: 'EMAIL_CONFIRM',
  LICENSES: 'LICENSES',
  NEW_FEATURES: 'NEW_FEATURES',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  USER: 'USER',
};

export default QueryKey;
